name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron:  '0 3 * * *' # 3am every day
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.12'
    - run: cabal run
