name: ci
on:
  push:
  pull_request:
  schedule:
  - cron:  '0 3 * * *' # 3am every day
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '9.0'
    - run: cabal run
